from typing import Protocol, Optional
from .entities import UserEntity, OTPCode

class UserRepository(Protocol):
    def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    def create_user(self, email: str, username: str, password: str) -> UserEntity: ...

class OTPRepository(Protocol):
    def create_code(self, user_id: int, purpose: str) -> OTPCode: ...
    def verify_code(self, user_id: int, purpose: str, code: str) -> bool: ...